# Generated by Django 4.0.7 on 2022-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
