# Generated by Django 3.0.7 on 2020-10-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalVenda',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('genre', models.CharField(max_length=50, verbose_name='Gênero')),
                ('publisher', models.CharField(max_length=50, verbose_name='Publisher')),
                ('na_sales', models.FloatField(verbose_name='NA Sales')),
                ('eu_sales', models.FloatField(verbose_name='EU Sales')),
                ('jp_sales', models.FloatField(verbose_name='JP Sales')),
                ('other_sales', models.FloatField(verbose_name='Other Sales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical venda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
