# Generated by Django 3.0.7 on 2020-10-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20201019_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='HistoricalVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
