# Generated by Django 3.0.7 on 2020-12-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Numéro')),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Máximo')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CR', 'Crédito'), ('DR', 'Débito')], max_length=2, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='internet_banking.Account', verbose_name='Conta')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='internet_banking.Client', verbose_name='Cliente'),
        ),
    ]
